# Generated by Django 6.0.7 on 2026-07-23 12:01

import apps.reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidyScanRequest',
            fields=[
                ('id', models.CharField(default=apps.reports.models.generate_short_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('property_address', models.CharField(help_text='Street name and house number', max_length=255)),
                ('postal_code', models.CharField(max_length=10)),
                ('place_of_residence', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('home', 'Home (Private home)'), ('vve', 'Homeowners Association (Apartment / VvE)'), ('rental', 'Rental property (Investment / rental)'), ('commercial', 'Commercial building')], default='home', max_length=20)),
                ('construction_year_period', models.CharField(blank=True, choices=[('before_1920', 'Before 1920'), ('1920_1945', '1920 - 1945'), ('1946_1970', '1946 - 1970'), ('1971_1990', '1971 - 1990'), ('1991_2010', '1991 - 2010'), ('after_2010', 'After 2010')], max_length=20)),
                ('is_own_property', models.BooleanField(default=True, help_text='Is the property your property?')),
                ('reported_damage_before', models.BooleanField(help_text='Have you reported damage before?')),
                ('received_decision', models.BooleanField(blank=True, help_text='Have you already received a decision? (optional)', null=True)),
                ('comments', models.TextField(blank=True)),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('is_contacted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Subsidy scan request',
                'ordering': ['-created_at'],
            },
        ),
    ]
