# Generated by Django 6.0.7 on 2026-07-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidies', '0002_alter_subsidyscanrequest_construction_year_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidyscanrequest',
            name='construction_year_period',
            field=models.CharField(blank=True, choices=[('before_1920', 'Before 1920'), ('1920_1945', '1920 - 1945'), ('1946_1970', '1946 - 1970'), ('1971_1990', '1971 - 1990'), ('1991_2010', '1991 - 2010'), ('after_2010', 'After 2010')], max_length=20),
        ),
    ]
