# Generated by Django 6.0.7 on 2026-07-23 12:08

import apps.helpRequest.models
import apps.reports.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.CharField(default=apps.reports.models.generate_short_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_number', models.CharField(default=apps.helpRequest.models.generate_request_number, editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(help_text='Street name and house number', max_length=255)),
                ('help_type', models.CharField(choices=[('claims_handling', 'Claims handling'), ('pre_shot', 'Pre shot'), ('second_opinion', 'Second opinion'), ('objection_procedures', 'Objection procedures'), ('repair_own_contractor', 'Repair own contractor'), ('otherwise', 'Otherwise')], default='second_opinion', max_length=30)),
                ('description', models.TextField(help_text='Describe your situation in as much detail as possible: when did it start, what does it look like, and are there any safety risks?')),
                ('contact_preference', models.CharField(choices=[('email', 'E-mail'), ('phone', 'Telephone'), ('both', 'Both')], default='email', max_length=10)),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Help request',
                'verbose_name_plural': 'Help requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpRequestAttachment',
            fields=[
                ('id', models.CharField(default=apps.reports.models.generate_short_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.helpRequest.models.help_request_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf', 'doc', 'docx'])])),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='helpRequest.helprequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
