# Generated by Django 6.0.7 on 2026-07-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpRequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='help_type',
            field=models.CharField(choices=[('claims_handling', 'Claims handling'), ('pre_shot', 'Pre shot'), ('second_opinion', 'Second opinion'), ('objection_procedures', 'Objection procedures'), ('repair_own_contractor', 'Repair own contractor'), ('otherwise', 'Otherwise'), ('legal_advice', 'Legal advice'), ('damage_claim_help', 'Damage claim help'), ('structural_inspection', 'Structural inspection'), ('subsidy_assistance', 'Subsidy assistance'), ('general_inquiry', 'General inquiry'), ('other', 'Other')], default='second_opinion', max_length=30),
        ),
    ]
