"""
Django settings for disaster project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
import environ
from corsheaders.defaults import default_headers

# Force redis-py to use RESP2 protocol to avoid HELLO command failures with older Redis versions
os.environ["REDIS_SERIALIZATION_PROTOCOL"] = "2"

try:
    import redis
    original_redis_init = redis.Connection.__init__
    def patched_redis_init(self, *args, **kwargs):
        kwargs["protocol"] = 2
        kwargs["maint_notifications_config"] = None
        original_redis_init(self, *args, **kwargs)
    redis.Connection.__init__ = patched_redis_init
except ImportError:
    pass


env = environ.Env(
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# settings/base.py → settings/ → disaster/ → project root
BASE_DIR = Path(__file__).resolve().parent.parent.parent

environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-disaster-management-by-morshed-nayeem')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=False)

ALLOWED_HOSTS = ['*']

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    "ngrok-skip-browser-warning",
]

# Trust reverse proxy SSL header (Nginx)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# CSRF Trusted Origins (reads from env + includes production domains & dev proxies)
csrf_trusted_env = env.list("CSRF_TRUSTED_ORIGINS", default=[])
CSRF_TRUSTED_ORIGINS = list(
    set(
        [
            "https://backend.bevingshulpnoord.com",
            "http://backend.bevingshulpnoord.com",
            "https://bevingshulpnoord.com",
            "http://bevingshulpnoord.com",
            "https://www.bevingshulpnoord.com",
            "http://www.bevingshulpnoord.com",
            "http://191.218.162.194",
            "https://191.218.162.194",
            "https://*.ngrok-free.app",
            "https://*.ngrok-free.dev",
            "https://*.ngrok.io",
            "http://localhost:3000",
            "http://127.0.0.1:3000",
        ]
        + csrf_trusted_env
    )
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # <-------Third-Party Apps--------->
    'rest_framework',
    'corsheaders',
    'django_celery_beat',
    'django_celery_results',


    # <----------Local Apps------------>
    'apps.core',
    'apps.reports',
    'apps.api',
    'apps.messages',
    'apps.subsidies',
    'apps.helpRequest',
    'apps.reviews',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'disaster.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'disaster.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# -------------------------
# Celery Configuration
# -------------------------
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 300  # 5 minutes hard limit

# Use django-celery-beat's database scheduler (manage periodic tasks via Django admin)
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Use django-celery-results to store task results in the database
CELERY_RESULT_BACKEND = "django-db"


# -------------------------
# Email Configuration (Lettermint)
# -------------------------
EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", default="smtp.lettermint.co")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="lettermint")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="Bevingshulp Noord <info@bevingshulpnoord.nl>")
ADMIN_EMAIL = env("ADMIN_EMAIL", default="info@bevingshulpnoord.nl")
LETTERMINT_API_KEY = env("LETTERMINT_API_KEY", default="")


# -------------------------
# ActiveCampaign CRM Integration
# -------------------------
# All values are env-driven.  Leave blank until the client provides
# real credentials — the AC client will silently no-op.
ACTIVECAMPAIGN_API_URL = env("ACTIVECAMPAIGN_API_URL", default="")
ACTIVECAMPAIGN_API_KEY = env("ACTIVECAMPAIGN_API_KEY", default="")
ACTIVECAMPAIGN_SCHADECHECK_PIPELINE_ID = env("ACTIVECAMPAIGN_SCHADECHECK_PIPELINE_ID", default="")
ACTIVECAMPAIGN_SUBSIDIESCAN_PIPELINE_ID = env("ACTIVECAMPAIGN_SUBSIDIESCAN_PIPELINE_ID", default="")
ACTIVECAMPAIGN_NEW_LEADS_STAGE_ID = env("ACTIVECAMPAIGN_NEW_LEADS_STAGE_ID", default="")
ACTIVECAMPAIGN_SUBSIDIESCAN_NEW_LEADS_STAGE_ID = env("ACTIVECAMPAIGN_SUBSIDIESCAN_NEW_LEADS_STAGE_ID", default="")
ACTIVECAMPAIGN_CASE_NUMBER_FIELD_ID = env("ACTIVECAMPAIGN_CASE_NUMBER_FIELD_ID", default="")
ACTIVECAMPAIGN_WEBHOOK_SECRET = env("ACTIVECAMPAIGN_WEBHOOK_SECRET", default="")


# -------------------------
# Google Places / Reviews Configuration
# -------------------------
GOOGLE_PLACES_API_KEY = env("GOOGLE_PLACES_API_KEY", default="")
GOOGLE_PLACE_ID = env("GOOGLE_PLACE_ID", default="ChIJZZtq0ms1x0cRlnzKtwRxopo")
GOOGLE_BUSINESS_FID = env("GOOGLE_BUSINESS_FID", default="0x47c5b5bb3a6a9b65:0x8ba67104b7ca7c96")
GOOGLE_BUSINESS_CID = env("GOOGLE_BUSINESS_CID", default="10062953288126758038")
GOOGLE_REVIEWS_CACHE_TIMEOUT = env.int("GOOGLE_REVIEWS_CACHE_TIMEOUT", default=86400)
