# Generated by Django 6.0.7 on 2026-07-10 13:34

import apps.reports.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.CharField(default=apps.reports.models.generate_short_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_number', models.CharField(default=apps.reports.models.generate_case_number, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(help_text='Street name and house number', max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('building_type', models.CharField(choices=[('residential', 'Residential / House (Woning)'), ('vve', 'VvE (Homeowners Association) (VVE)'), ('commercial', 'Commercial property (Bedrijfspand)'), ('investment', 'Investment / Rental property (Belegging / verhuur)')], default='residential', max_length=20)),
                ('applicable_case', models.CharField(choices=[('new_report', 'New damage report (Nieuwe schademelding)'), ('recording_before_renovation', 'Recording before renovation'), ('second_opinion', 'Second opinion on ongoing file'), ('objection_review', 'Objection or review (Bezwaar of herziening)'), ('other', 'Other')], default='new_report', max_length=30)),
                ('description', models.TextField(help_text='Describe the damage in as much detail as possible.')),
                ('contact_preference', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('both', 'Both')], default='email', max_length=10)),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('under_review', 'Under review'), ('in_progress', 'In progress'), ('approved', 'Approved'), ('completed', 'Completed')], default='received', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.CharField(default=apps.reports.models.generate_short_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('under_review', 'Under review'), ('in_progress', 'In progress'), ('approved', 'Approved'), ('completed', 'Completed')], help_text='Status this update corresponds to on the progress timeline.', max_length=20)),
                ('note', models.TextField(help_text="Text shown to the applicant, e.g. 'Your application has been reviewed and forwarded for further processing.'")),
                ('damage_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='reports.damagereport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DamageReportAttachment',
            fields=[
                ('id', models.CharField(default=apps.reports.models.generate_short_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.reports.models.damage_report_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf', 'doc', 'docx'])])),
                ('damage_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.damagereport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
