# Generated by Django 6.0.7 on 2026-07-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseupdate',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('under_review', 'Under review'), ('in_progress', 'In progress'), ('approved', 'Approved'), ('completed', 'Completed')], default='received', help_text='Status this update corresponds to on the progress timeline.', max_length=20),
        ),
    ]
