# Generated by Django 6.0.7 on 2026-07-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_caseupdate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseupdate',
            name='note',
            field=models.TextField(default='Application recieved. You have recieved a confirmation email.', help_text="Text shown to the applicant, e.g. 'Your application has been reviewed and forwarded for further processing.'"),
        ),
    ]
