# Generated by Django 6.0.7 on 2026-07-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_caseupdate_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagereport',
            name='status',
        ),
    ]
