# Generated by Django 6.0.7 on 2026-07-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_damagereport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseupdate',
            name='note',
            field=models.TextField(help_text="Text shown to the applicant, e.g. 'Your application has been reviewed and forwarded for further processing.'"),
        ),
    ]
