# Generated by Django 6.0.7 on 2026-07-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_caseupdate_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseupdate',
            options={'ordering': ['created_at']},
        ),
    ]
