# Generated by Django 6.0.7 on 2026-07-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_caseupdate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseupdate',
            name='status',
            field=models.CharField(choices=[('new_lead', 'New Leads'), ('first_contact', 'First Contact'), ('no_contact', 'No Contact (Second Attempt)'), ('inspection_scheduled', 'Inspection Appointment Scheduled'), ('disqualified', 'Disqualified'), ('contract_signed', 'Client / Contract Signed'), ('damage_reported', 'Earthquake Damage Reported'), ('state_inspection', 'State Inspection at Property'), ('waiting_for_report', 'Waiting for Report'), ('invoice_processed', 'Invoice Processed / Payout'), ('received', 'Received'), ('under_review', 'Under review'), ('in_progress', 'In progress'), ('approved', 'Approved'), ('completed', 'Completed')], default='received', help_text='Status this update corresponds to on the progress timeline.', max_length=20),
        ),
    ]
