# Generated by Django 6.0.7 on 2026-07-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_caseupdate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='activecampaign_deal_id',
            field=models.CharField(blank=True, help_text='ActiveCampaign Deal ID for CRM sync.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='caseupdate',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('under_review', 'Under review'), ('in_progress', 'In progress'), ('approved', 'Approved'), ('completed', 'Completed')], default='received', help_text='Status this update corresponds to on the progress timeline.', max_length=20),
        ),
    ]
