# Generated by Django 6.0.7 on 2026-07-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_damagereport_activecampaign_deal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='comments',
            field=models.TextField(blank=True, default='', help_text='Any additional information that is important to us.'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='damage_reported_before',
            field=models.BooleanField(default=False, help_text='Has damage been reported before?'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='damage_scope',
            field=models.JSONField(blank=True, default=list, help_text='List of damage aspects e.g. damage_inside, damage_outside, subsidence'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='is_own_property',
            field=models.BooleanField(default=True, help_text='Is the property your property?'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='applicable_case',
            field=models.CharField(blank=True, choices=[('new_report', 'New damage report (Nieuwe schademelding)'), ('recording_before_renovation', 'Recording before renovation'), ('second_opinion', 'Second opinion on ongoing file'), ('objection_review', 'Objection or review (Bezwaar of herziening)'), ('other', 'Other')], default='new_report', max_length=30),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='building_type',
            field=models.CharField(choices=[('home', 'Home (Private home)'), ('vve', 'Homeowners Association (Apartment / Homeowners Association)'), ('rental', 'Rental property (Investment / rental)'), ('commercial', 'Commercial building (Commercial property)'), ('residential', 'Residential / House (Woning)'), ('investment', 'Investment / Rental property (Belegging / verhuur)')], default='home', max_length=20),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='contact_preference',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('both', 'Both')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Describe the damage in as much detail as possible.'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
